from frontend.themes.base_theme import (
    ThemeTokens, ColorTokens, TypographyTokens, SpacingTokens, RadiusTokens,
    ShadowTokens, ShadowConfig, ElevationTokens, ElevationConfig,
    BorderTokens, AnimationTokens, IconTokens, GradientTokens,
    TextureTokens, LEDTokens, StatusColorTokens, LayoutTokens,
)

def make_modern_tokens() -> ThemeTokens:
    return ThemeTokens(
        colors=ColorTokens(
            background       = "#0F0F11",
            surface          = "#171719",
            surface_elevated = "#1E1E22",
            surface_hover    = "#28282D",
            muted            = "#121214",
            text_primary     = "#F0F0F0",
            text_secondary   = "#A0A0A5",
            text_muted       = "#707075",
            text_disabled    = "#404045",
            text_inverse     = "#0F0F11",
            accent           = "#4B96FF",
            accent_dim       = "#2F66B5",
            accent_hover     = "#65A6FF",
            accent_fg        = "#FFFFFF",
            border           = "#28282D",
            border_light     = "#38383D",
            border_dark      = "#1F1F24",
            selection        = "#2F66B5",
        ),
        typography=TypographyTokens(
            family_sans      = "Inter",
            family_mono      = "JetBrains Mono",
            family_full_sans = "Inter, sans-serif",
            family_full_mono = "JetBrains Mono, monospace",
            size_xs   = 10,
            size_sm   = 12,
            size_base = 14,
            size_lg   = 16,
            size_xl   = 18,
            size_2xl  = 20,
            size_3xl  = 28,
            weight_regular  = 400,
            weight_medium   = 500,
            weight_semibold = 600,
            weight_bold     = 700,
            weight_black    = 900,
        ),
        spacing=SpacingTokens(
            px2=2, px4=4, px8=8, px12=12, px16=16,
            px20=20, px24=24, px32=32, px40=40, px48=48,
            px64=64, px96=96,
        ),
        radius=RadiusTokens(
            none=0, sm=4, md=8, lg=12, xl=16, xxl=24, full=999,
        ),
        shadows=ShadowTokens(
            card=ShadowConfig(
                dark_x=0, dark_y=4, dark_blur=12, dark_color="#00000040",
                light_x=0, light_y=0, light_blur=0, light_color="#00000000",
            ),
            floating=ShadowConfig(
                dark_x=0, dark_y=8, dark_blur=24, dark_color="#00000080",
                light_x=0, light_y=0, light_blur=0, light_color="#00000000",
            ),
            pressed=ShadowConfig(inset=True,
                dark_x=0, dark_y=1, dark_blur=2, dark_color="#00000020",
                light_x=0, light_y=0, light_blur=0, light_color="#00000000",
            ),
            recessed=ShadowConfig(inset=True,
                dark_x=0, dark_y=2, dark_blur=4, dark_color="#00000015",
                light_x=0, light_y=0, light_blur=0, light_color="#00000000",
            ),
            glow=ShadowConfig(
                dark_x=0, dark_y=0, dark_blur=16,
                glow_color="#4B96FF", glow_radius=16,
            ),
        ),
        elevation=ElevationTokens(
            chassis  = ElevationConfig(level=0,  label="base"),
            panel    = ElevationConfig(level=1,  label="panel"),
            floating = ElevationConfig(level=2,  label="floating"),
            recessed = ElevationConfig(level=-1, label="recessed"),
        ),
        borders=BorderTokens(
            width_thin=1, width_medium=2, width_thick=3,
            style_solid="solid", style_dashed="dashed",
        ),
        animation=AnimationTokens(
            duration_fast   = 100,
            duration_normal = 200,
            duration_slow   = 400,
            easing_spring   = 0,
            easing_out      = 16,
            easing_in_out   = 17,
            easing_bounce   = 0,
            easing_linear   = 0,
            led_pulse_period_ms = 0,
        ),
        icons=IconTokens(
            size_xs=12, size_sm=16, size_md=20, size_lg=24, size_xl=32,
            stroke_thin=1.0, stroke_normal=1.5, stroke_bold=2.0,
        ),
        gradients=GradientTokens(
            chassis_noise_alpha=0.0,
            lighting_hotspot_alpha=0.0,
            radial_tint_color="#4B96FF",
            button_top_alpha=0.0,
            button_bottom_alpha=0.0,
        ),
        textures=TextureTokens(
            noise_enabled=False,
            carbon_enabled=False,
            noise_opacity=0.0,
            carbon_opacity=0.0,
        ),
        led=LEDTokens(
            dot_size=8,
            glow_radius=8,
            pulse_enabled=True,
            pulse_period_ms=2000,
            online_color="#55FF55",
            warn_color="#FFB86C",
            error_color="#FF5555",
            info_color="#4B96FF",
            offline_color="#707075",
        ),
        status=StatusColorTokens(
            success="#55FF55",
            warning="#FFB86C",
            danger="#FF5555",
            info="#4B96FF",
            busy="#A0A0A5",
            offline="#707075",
        ),
        layout=LayoutTokens(
            sidebar_width      = 250,
            toolbar_height     = 48,
            statusbar_height   = 32,
            navigation_width   = 250,
            panel_margin       = 24,
            window_padding     = 16,
            content_padding    = 24,
            section_gap        = 16,
            grid_gap           = 16,
            dialog_min_width   = 400,
            dialog_min_height  = 300,
            splitter_handle_px = 4,
            card_padding       = 20,
            input_min_height   = 40,
            button_min_height  = 40,
            touch_target_min   = 44,
        ),
    )
