"""
Domain Model: Interview Blueprint.

An Interview Blueprint defines the structure, goals, and constraints
of a specific interview before it begins. It acts as the "lesson plan"
for the InterviewEngine.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from uuid import UUID, uuid4

from backend.shared.enums.session import DifficultyLevel, InterviewType


@dataclass
class InterviewBlueprint:
    """
    Core domain entity defining the setup for an interview.

    A blueprint is typically generated by merging a Resume and a
    Job Description, instructing the AI on what skills to target.

    Attributes:
        blueprint_id: Unique identifier for this blueprint.
        user_id: The ID of the user who owns this blueprint.
        title: Human-readable name (e.g., "Senior Python Dev Mock").
        interview_type: The overall style of the interview.
        difficulty: Desired strictness/complexity.
        target_role: The specific job title being interviewed for.
        topics: List of specific technical or behavioral topics to cover.
        system_prompt_template: The identifier for the base persona prompt.
        created_at: When the blueprint was created.
    """

    user_id: UUID
    title: str
    interview_type: InterviewType
    difficulty: DifficultyLevel
    target_role: str = ""
    topics: list[str] = field(default_factory=list)
    system_prompt_template: str = "default_interviewer"
    blueprint_id: UUID = field(default_factory=uuid4)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
